export const CART_REQUEST_ITEM = "CART_REQUEST_ITEM"
export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

export const SHIPPING_ADDRESS_SUCCESS = "SHIPPING_ADDRESS_SUCCESS"
export const PAYMENT_METHOD_SUCCESS = "PAYMENT_METHOD_SUCCESS"