# Generated by Django 4.0.5 on 2022-06-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInstocked',
            new_name='countInstock',
        ),
    ]
