# Generated by Django 4.0.5 on 2022-06-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_countinstocked_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInstock',
            new_name='countInStock',
        ),
    ]
