# Generated by Django 4.0.5 on 2022-07-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='countInstocked',
            new_name='qty',
        ),
    ]
